import path from "node:path";
import { CfnOutput, Duration, RemovalPolicy, Stack, type StackProps } from "aws-cdk-lib";
import * as budgets from "aws-cdk-lib/aws-budgets";
import * as acm from "aws-cdk-lib/aws-certificatemanager";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as origins from "aws-cdk-lib/aws-cloudfront-origins";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import type * as dsql from "aws-cdk-lib/aws-dsql";
import * as iam from "aws-cdk-lib/aws-iam";
import * as lambda from "aws-cdk-lib/aws-lambda";
import { SqsEventSource } from "aws-cdk-lib/aws-lambda-event-sources";
import * as logs from "aws-cdk-lib/aws-logs";
import * as route53 from "aws-cdk-lib/aws-route53";
import * as targets from "aws-cdk-lib/aws-route53-targets";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as s3deploy from "aws-cdk-lib/aws-s3-deployment";
import * as sns from "aws-cdk-lib/aws-sns";
import * as subscriptions from "aws-cdk-lib/aws-sns-subscriptions";
import * as cloudwatch from "aws-cdk-lib/aws-cloudwatch";
import * as cwActions from "aws-cdk-lib/aws-cloudwatch-actions";
import * as sqs from "aws-cdk-lib/aws-sqs";
import * as ssm from "aws-cdk-lib/aws-ssm";
import type { Construct } from "constructs";
import { appViewerRequest } from "./cloudfront-functions.js";

export interface AppStackProps extends StackProps {
  /** From DataStack. */
  cluster: dsql.CfnCluster;
  bucketName: string;
  bucketArn: string;
  /** dist/aws from infrastructure/aws/opennext.Dockerfile or the CI build. */
  bundleDir: string;
  siteUrl: string;
  domain?: string;
  hostedZone?: route53.IHostedZone;
  /** us-east-1 ACM certificate for the domain, requested outside CDK. */
  certificateArn?: string;
  certificate?: acm.ICertificate;
  originSecret: string;
  analyticsSalt: string;
  alertEmail?: string;
}

/** Database role the app connects as (mapped to the Lambda's IAM role by `pnpm db:migrate:dsql --grant-app-role`). */
export const APP_DB_USER = "usba_app";
const DISTRIBUTION_ID_PARAMETER = "/usba/cdn-distribution-id";

/**
 * Everything is chosen to stay inside AWS always-free allowances (ADR 0014):
 * - Lambda (1M requests, 400k GB-s), DynamoDB provisioned capacity (25 RCU/WCU),
 *   SQS (1M requests), Aurora DSQL (100k DPUs, 1 GB), CloudWatch Logs with
 *   1-week retention.
 * - CloudFront: always-free 1 TB and 10M requests a month on standard pricing
 *   (AWS "project" accounts can't attach WAF, so the flat-rate plan isn't used).
 *   On a standard account it can be subscribed to the flat-rate Free plan.
 * - No NAT gateway, load balancer, public IPv4, RDS, Secrets Manager, API
 *   Gateway or Lambda@Edge.
 */
export class AppStack extends Stack {
  constructor(scope: Construct, id: string, props: AppStackProps) {
    super(scope, id, props);
    const bundle = (p: string) => path.join(props.bundleDir, p);

    /* ---------------------------------------------------------------- */
    /* Data                                                              */
    /* ---------------------------------------------------------------- */

    const { cluster } = props;
    const certificate =
      props.certificate ??
      (props.certificateArn
        ? acm.Certificate.fromCertificateArn(this, "Certificate", props.certificateArn)
        : undefined);
    // Imported by name: DataStack's bucket policy already lets CloudFront read
    // it, so this stack never edits that policy (no cross-stack cycle).
    const bucket = s3.Bucket.fromBucketAttributes(this, "SiteBucket", {
      bucketName: props.bucketName,
      bucketArn: props.bucketArn,
    });

    // OpenNext tag cache (dynamodb-nextMode). Provisioned capacity is what the
    // always-free tier covers; on-demand is not.
    const tagCache = new dynamodb.Table(this, "TagCache", {
      partitionKey: { name: "tag", type: dynamodb.AttributeType.STRING },
      sortKey: { name: "path", type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PROVISIONED,
      readCapacity: 5,
      writeCapacity: 5,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    // Stale pages are queued here and regenerated by the revalidation function
    // (OpenNext awaits the enqueue inside the visitor's request; SQS is fast).
    const revalidationQueue = new sqs.Queue(this, "Revalidation", {
      fifo: true,
      contentBasedDeduplication: true,
      receiveMessageWaitTime: Duration.seconds(20),
      visibilityTimeout: Duration.seconds(60),
      enforceSSL: true,
    });

    /* ---------------------------------------------------------------- */
    /* Server function                                                   */
    /* ---------------------------------------------------------------- */

    const logGroup = new logs.LogGroup(this, "ServerLogs", {
      retention: logs.RetentionDays.ONE_WEEK,
      removalPolicy: RemovalPolicy.DESTROY,
    });
    const mediaBaseUrl = `${props.siteUrl}/media`;
    const server = new lambda.Function(this, "Server", {
      description: "USBA store (Next.js via OpenNext)",
      runtime: lambda.Runtime.NODEJS_22_X,
      architecture: lambda.Architecture.X86_64,
      handler: "index.handler",
      code: lambda.Code.fromAsset(bundle("server-function.zip")),
      memorySize: 1024,
      timeout: Duration.seconds(30),
      logGroup,
      environment: {
        NODE_ENV: "production",
        SITE_URL: props.siteUrl,
        DATABASE_URL: `postgres://${APP_DB_USER}@${cluster.attrEndpoint}:5432/postgres`,
        DATABASE_AUTH: "dsql-iam",
        DATABASE_SSL: "verify-full",
        DATABASE_POOL_MAX: "2",
        S3_BUCKET: bucket.bucketName,
        S3_REGION: this.region,
        S3_KEY_PREFIX: "media/",
        MEDIA_BASE_URL: mediaBaseUrl,
        CLIENT_IP_HEADER: "cloudfront-viewer-address",
        ORIGIN_VERIFY_SECRET: props.originSecret,
        ANALYTICS_SALT: props.analyticsSalt,
        CDN_DISTRIBUTION_ID_PARAMETER: DISTRIBUTION_ID_PARAMETER,
        // OpenNext caches
        CACHE_BUCKET_NAME: bucket.bucketName,
        CACHE_BUCKET_KEY_PREFIX: "_cache",
        CACHE_BUCKET_REGION: this.region,
        CACHE_DYNAMO_TABLE: tagCache.tableName,
        REVALIDATION_QUEUE_URL: revalidationQueue.queueUrl,
        REVALIDATION_QUEUE_REGION: this.region,
      },
    });
    revalidationQueue.grantSendMessages(server);
    bucket.grantReadWrite(server, "_cache/*");
    bucket.grantReadWrite(server, "media/*");
    bucket.grantDelete(server, "media/*");
    tagCache.grantReadWriteData(server);
    server.addToRolePolicy(
      new iam.PolicyStatement({ actions: ["dsql:DbConnect"], resources: [cluster.attrResourceArn] }),
    );
    server.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ["cloudfront:CreateInvalidation"],
        resources: [`arn:${this.partition}:cloudfront::${this.account}:distribution/*`],
      }),
    );
    server.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ["ssm:GetParameter"],
        resources: [
          `arn:${this.partition}:ssm:${this.region}:${this.account}:parameter${DISTRIBUTION_ID_PARAMETER}`,
        ],
      }),
    );

    // Public URL (OAC can't sign browser POST bodies, which Server Actions need);
    // src/proxy.ts rejects requests without CloudFront's x-origin-verify header.
    const functionUrl = server.addFunctionUrl({
      authType: lambda.FunctionUrlAuthType.NONE,
      invokeMode: lambda.InvokeMode.RESPONSE_STREAM,
    });

    // Sends HEAD requests with the build's revalidation token to the Function
    // URL (allowed by the origin lock in src/proxy.ts).
    const revalidation = new lambda.Function(this, "Revalidator", {
      description: "USBA store: regenerates stale pages from the revalidation queue",
      runtime: lambda.Runtime.NODEJS_22_X,
      architecture: lambda.Architecture.X86_64,
      handler: "index.handler",
      code: lambda.Code.fromAsset(bundle("revalidation-function.zip")),
      memorySize: 256,
      timeout: Duration.seconds(30),
      logGroup: new logs.LogGroup(this, "RevalidatorLogs", {
        retention: logs.RetentionDays.ONE_WEEK,
        removalPolicy: RemovalPolicy.DESTROY,
      }),
    });
    revalidation.addEventSource(new SqsEventSource(revalidationQueue, { batchSize: 5 }));

    /* ---------------------------------------------------------------- */
    /* CloudFront                                                        */
    /* ---------------------------------------------------------------- */

    const serverOrigin = new origins.FunctionUrlOrigin(functionUrl, {
      customHeaders: { "x-origin-verify": props.originSecret },
      readTimeout: Duration.seconds(30),
    });
    const assetsOrigin = origins.S3BucketOrigin.withOriginAccessControl(bucket, { originPath: "/_assets" });
    const mediaOrigin = origins.S3BucketOrigin.withOriginAccessControl(bucket);

    const serverCache = new cloudfront.CachePolicy(this, "ServerCache", {
      comment: "Next.js pages: honour s-maxage from the app; vary on RSC request headers",
      minTtl: Duration.seconds(0),
      defaultTtl: Duration.seconds(0),
      maxTtl: Duration.days(365),
      queryStringBehavior: cloudfront.CacheQueryStringBehavior.all(),
      headerBehavior: cloudfront.CacheHeaderBehavior.allowList(
        "rsc",
        "next-router-prefetch",
        "next-router-state-tree",
        "next-router-segment-prefetch",
        "next-url",
      ),
      cookieBehavior: cloudfront.CacheCookieBehavior.none(),
      enableAcceptEncodingGzip: true,
      enableAcceptEncodingBrotli: true,
    });
    const appRequest = new cloudfront.Function(this, "AppViewerRequest", {
      runtime: cloudfront.FunctionRuntime.JS_2_0,
      code: cloudfront.FunctionCode.fromInline(appViewerRequest(props.domain)),
    });
    const staticBehavior: cloudfront.BehaviorOptions = {
      origin: assetsOrigin,
      viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
      compress: true,
    };

    const distribution = new cloudfront.Distribution(this, "Cdn", {
      comment: "USBA store",
      defaultBehavior: {
        origin: serverOrigin,
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
        cachePolicy: serverCache,
        originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
        functionAssociations: [
          { function: appRequest, eventType: cloudfront.FunctionEventType.VIEWER_REQUEST },
        ],
        compress: true,
      },
      additionalBehaviors: {
        "_next/*": staticBehavior,
        "brand/*": staticBehavior,
        "usba-logo.png": staticBehavior,
        BUILD_ID: staticBehavior,
        "media/*": { ...staticBehavior, origin: mediaOrigin },
      },
      domainNames: props.domain ? [props.domain, `www.${props.domain}`] : undefined,
      certificate,
      httpVersion: cloudfront.HttpVersion.HTTP2_AND_3,
      minimumProtocolVersion: certificate ? cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021 : undefined,
      priceClass: cloudfront.PriceClass.PRICE_CLASS_ALL,
    });

    new ssm.StringParameter(this, "DistributionIdParameter", {
      parameterName: DISTRIBUTION_ID_PARAMETER,
      stringValue: distribution.distributionId,
      description: "Read by the server function to invalidate CloudFront after admin saves.",
    });

    if (props.domain && props.hostedZone) {
      for (const recordName of [props.domain, `www.${props.domain}`]) {
        const target = route53.RecordTarget.fromAlias(new targets.CloudFrontTarget(distribution));
        new route53.ARecord(this, `A-${recordName}`, { zone: props.hostedZone, recordName, target });
        new route53.AaaaRecord(this, `AAAA-${recordName}`, { zone: props.hostedZone, recordName, target });
      }
    }

    /* ---------------------------------------------------------------- */
    /* Build output → S3                                                 */
    /* ---------------------------------------------------------------- */

    // Hashed build files never change: cache them for a year. Old ones are kept
    // (prune: false) so open tabs from the previous release keep working.
    new s3deploy.BucketDeployment(this, "DeployNextStatic", {
      sources: [s3deploy.Source.asset(bundle("assets/_next"))],
      destinationBucket: bucket,
      destinationKeyPrefix: "_assets/_next",
      cacheControl: [s3deploy.CacheControl.fromString("public,max-age=31536000,immutable")],
      prune: false,
      memoryLimit: 512,
    });
    new s3deploy.BucketDeployment(this, "DeployPublicFiles", {
      sources: [s3deploy.Source.asset(bundle("assets"), { exclude: ["_next", "_next/*"] })],
      destinationBucket: bucket,
      destinationKeyPrefix: "_assets",
      exclude: ["_next/*"],
      cacheControl: [s3deploy.CacheControl.fromString("public,max-age=0,s-maxage=31536000,must-revalidate")],
      prune: false,
      memoryLimit: 512,
    });
    // Prerendered pages for this build; one "/*" invalidation per deploy.
    const deployCache = new s3deploy.BucketDeployment(this, "DeployCache", {
      sources: [s3deploy.Source.asset(bundle("cache"))],
      destinationBucket: bucket,
      destinationKeyPrefix: "_cache",
      prune: true,
      memoryLimit: 512,
      distribution,
      distributionPaths: ["/*"],
    });
    // Invalidate only once the new server code is live; otherwise requests in
    // between put the previous release's pages back into CloudFront.
    deployCache.node.addDependency(server);

    /* ---------------------------------------------------------------- */
    /* Alarms (free tier: 10 alarms, 1,000 SNS emails a month)           */
    /* ---------------------------------------------------------------- */

    if (props.alertEmail) {
      const alerts = new sns.Topic(this, "Alerts", { displayName: "USBA store alerts" });
      alerts.addSubscription(new subscriptions.EmailSubscription(props.alertEmail));
      const notify = new cwActions.SnsAction(alerts);
      const alarm = (id: string, metric: cloudwatch.IMetric, description: string, threshold = 1) =>
        new cloudwatch.Alarm(this, id, {
          metric,
          threshold,
          evaluationPeriods: 1,
          comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
          treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
          alarmDescription: description,
        }).addAlarmAction(notify);
      const fiveMinutes = { period: Duration.minutes(5), statistic: "Sum" };
      alarm(
        "ServerErrors",
        server.metricErrors(fiveMinutes),
        "The site's Lambda function failed (pages or admin may be showing errors). Check the ServerLogs log group.",
      );
      alarm(
        "ServerThrottles",
        server.metricThrottles(fiveMinutes),
        "Requests were throttled: the account's Lambda concurrency limit was reached.",
      );
      alarm(
        "RevalidatorErrors",
        revalidation.metricErrors(fiveMinutes),
        "Background page regeneration failed; pages may stay stale until the next visit or admin save.",
      );
      alarm(
        "RevalidationBacklog",
        revalidationQueue.metricApproximateAgeOfOldestMessage({
          period: Duration.minutes(5),
          statistic: "Maximum",
        }),
        "Stale-page regeneration requests have been waiting over 15 minutes.",
        900,
      );
    }

    /* ---------------------------------------------------------------- */
    /* Cost guard                                                        */
    /* ---------------------------------------------------------------- */

    if (props.alertEmail) {
      // Budget notifications are free. Alerts on any actual spend over $0.01.
      new budgets.CfnBudget(this, "ZeroSpend", {
        budget: {
          budgetName: "usba-zero-spend",
          budgetType: "COST",
          timeUnit: "MONTHLY",
          budgetLimit: { amount: 1, unit: "USD" },
        },
        notificationsWithSubscribers: [
          {
            notification: {
              notificationType: "ACTUAL",
              comparisonOperator: "GREATER_THAN",
              threshold: 1,
              thresholdType: "PERCENTAGE",
            },
            subscribers: [{ subscriptionType: "EMAIL", address: props.alertEmail }],
          },
        ],
      });
    }

    new CfnOutput(this, "SiteUrl", { value: props.siteUrl });
    new CfnOutput(this, "DistributionDomain", { value: distribution.distributionDomainName });
    new CfnOutput(this, "DistributionId", { value: distribution.distributionId });
    new CfnOutput(this, "ServerRoleArn", { value: server.role?.roleArn ?? "" });
  }
}
