import type { OpenNextConfig } from "@opennextjs/aws/types/open-next.js";

/**
 * OpenNext build for AWS Lambda (ADR 0014). One server function behind a
 * Lambda Function URL (response streaming, so PPR shells flush early) and
 * CloudFront. The "-lite" overrides sign requests with aws4fetch instead of
 * bundling the AWS SDK, which keeps the function small and cold starts short.
 *
 * - incrementalCache s3-lite: prerendered pages and `use cache` entries in S3
 * - tagCache dynamodb-nextMode: per-tag revalidation timestamps, which is what
 *   updateTag()/revalidateTag() need (see src/server/cache.ts)
 * - queue sqs-lite: stale pages are regenerated by the revalidation function
 *
 * proxy.ts (Node runtime) is bundled into the server function, so there is no
 * Lambda@Edge (billed separately on the CloudFront flat-rate plan).
 *
 * CDN invalidation is done by src/server/cdn.ts with a single "/*" path per
 * admin save; OpenNext's per-path "cloudfront" handler would use hundreds of
 * the 1,000 free monthly invalidation paths per catalogue change.
 */
// OPEN_NEXT_LOCAL=1 builds a variant whose caches live on the function's file
// system, so the real Lambda handler can be exercised locally without AWS
// (infrastructure/aws/local/harness.mjs). Never deploy that variant.
const local = process.env.OPEN_NEXT_LOCAL === "1";

const config = {
  default: {
    override: {
      // OpenNext's aws-lambda-streaming wrapper plus a Content-Length fix for
      // compressed cached pages (infrastructure/aws/opennext/streaming-wrapper.ts).
      wrapper: () => import("./infrastructure/aws/opennext/streaming-wrapper").then((m) => m.default),
      converter: "aws-apigw-v2",
      incrementalCache: local ? "fs-dev" : "s3-lite",
      tagCache: local ? "fs-dev-nextMode" : "dynamodb-nextMode",
      // OpenNext awaits queue.send() inside the visitor's request, so production
      // hands stale pages to SQS (a ~20 ms call) and the revalidation function
      // regenerates them. "direct" regenerates inline: fine locally only.
      queue: local ? "direct" : "sqs-lite",
    },
    // OpenNext strips sharp from the server function (it normally only serves
    // next/image, which this app doesn't use). Admin uploads need it, so install
    // the Lambda platform build (linux x64, glibc) explicitly.
    install: { packages: ["sharp@0.35.5"], arch: "x64", libc: "glibc", os: "linux" },
  },
  buildCommand: "pnpm build",
} satisfies OpenNextConfig;

export default config;
